### PR TITLE
All the work from 01/4/2016

### PR DESCRIPTION
**Pull request by minaorangina**

### CODE REVIEW

**Comment by iteles** [comment]
LOL at this PR name :wink:

**Comment by minaorangina** [comment]
#closes #40

**Comment by mk4111** [comment]
Hi @Danwhy  sorry for assigning this pull request to you over the weekend - we by no means ask for it to be looked at this weekend, but if you could merge it some time on Monday, we'd really appreciate it!! 
Thank you!

**Comment by minaorangina** [comment]
@mk4111 just wondering about the `/price` route.  It's nested within the `/travel-post` route, but also appears outside it.  Was just curious why?  

This is what i mean:
screen shot 2016-04-03 at 11 46 46

**Comment by mk4111** [comment]
So the same component can be referenced in more than one place, and I was
thinking of making a /send-post/price route for the sender.

I just left the /price route there so that I'd remember to do that, but we
could delete it from there and I'll just make note to include it in the
/send-post

**Pull request merged**
